// <auto-generated />
using System;
using LoyaltySphere.RewardService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoyaltySphere.RewardService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260416235036_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoyaltySphere.EventBus.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("LoyaltySphere.RewardService.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BonusPoints")
                        .HasColumnType("numeric");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CampaignType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CashbackPercentage")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentParticipations")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxParticipations")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinimumTransactionAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PointsMultiplier")
                        .HasColumnType("numeric");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetCustomerSegment")
                        .HasColumnType("text");

                    b.Property<string>("TargetMerchantCategory")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Terms")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("LoyaltySphere.RewardService.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CustomerId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EnrolledAt");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LastName");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TenantId");

                    b.Property<int>("Tier")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("Tier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_customers_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_customers_is_active");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_customers_tenant_id");

                    b.HasIndex("Tier")
                        .HasDatabaseName("IX_customers_tier");

                    b.HasIndex("TenantId", "CustomerId")
                        .IsUnique()
                        .HasDatabaseName("IX_customers_tenant_customer_unique");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("LoyaltySphere.RewardService.Domain.Entities.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("CampaignId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CampaignId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CustomerExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CustomerExternalId");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("CustomerId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("IsProcessed");

                    b.Property<string>("MerchantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("MerchantId");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ProcessedAt");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ProcessingError");

                    b.Property<int>("RewardType")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("RewardType");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Source");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TenantId");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TransactionId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("IX_rewards_campaign_id");

                    b.HasIndex("CustomerExternalId")
                        .HasDatabaseName("IX_rewards_customer_external_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_rewards_customer_id");

                    b.HasIndex("RewardType")
                        .HasDatabaseName("IX_rewards_reward_type");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_rewards_tenant_id");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("IX_rewards_transaction_id");

                    b.HasIndex("TenantId", "CustomerId", "ProcessedAt")
                        .HasDatabaseName("IX_rewards_tenant_customer_processed");

                    b.ToTable("Rewards", (string)null);
                });

            modelBuilder.Entity("LoyaltySphere.RewardService.Domain.Entities.RewardRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaximumTransactionAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("MerchantCategory")
                        .HasColumnType("text");

                    b.Property<string>("MerchantId")
                        .HasColumnType("text");

                    b.Property<decimal?>("MinimumTransactionAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PointsPerUnit")
                        .HasColumnType("numeric");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ProductCategory")
                        .HasColumnType("text");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RewardRules");
                });

            modelBuilder.Entity("LoyaltySphere.RewardService.Domain.Entities.Customer", b =>
                {
                    b.OwnsOne("LoyaltySphere.RewardService.Domain.ValueObjects.Points", "LifetimePoints", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("LifetimePoints");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("LoyaltySphere.RewardService.Domain.ValueObjects.Points", "PointsBalance", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PointsBalance");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("LifetimePoints")
                        .IsRequired();

                    b.Navigation("PointsBalance")
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltySphere.RewardService.Domain.Entities.Reward", b =>
                {
                    b.HasOne("LoyaltySphere.RewardService.Domain.Entities.Customer", "Customer")
                        .WithMany("Rewards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("LoyaltySphere.RewardService.Domain.ValueObjects.Points", "PointsAwarded", b1 =>
                        {
                            b1.Property<Guid>("RewardId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PointsAwarded");

                            b1.HasKey("RewardId");

                            b1.ToTable("Rewards");

                            b1.WithOwner()
                                .HasForeignKey("RewardId");
                        });

                    b.OwnsOne("LoyaltySphere.RewardService.Domain.ValueObjects.Money", "TransactionAmount", b1 =>
                        {
                            b1.Property<Guid>("RewardId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TransactionAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("RewardId");

                            b1.ToTable("Rewards");

                            b1.WithOwner()
                                .HasForeignKey("RewardId");
                        });

                    b.Navigation("Customer");

                    b.Navigation("PointsAwarded")
                        .IsRequired();

                    b.Navigation("TransactionAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltySphere.RewardService.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Rewards");
                });
#pragma warning restore 612, 618
        }
    }
}
